export const selectOptions = [
  {
    name: "priority",
    options: [
      { value: "", text: "" },
      { value: "1", text: "Low" },
      { value: "2", text: "Medium" },
      { value: "3", text: "High" },
    ],
  },
  {
    name: "problem_category",
    options: [
      { value: "", text: "" },

      { value: "general_help", text: "General Help" },
      { value: "login_help", text: "Login Help" },
      { value: "missing_documents", text: "Missing Documents" },
      { value: "class_access", text: "Can't access your class?" },
      { value: "view_grades_help", text: "Can't see your grades?" },
      { value: "upload_help", text: "Upload Help" },
      { value: "download_help", text: "Download Help" },
      { value: "tigerware_support", text: "Tigerware support" },
      { value: "hardware_support", text: "Hardware support" },
    ],
  },
  {
    name: "department",
    options: [
      { value: "", text: "" },
      { value: "accounting", text: "Accounting" },
      {
        value: "administrative_foundation_se",
        text: "Administrative_Foundation_Se",
      },
      { value: "aerospace_studies", text: "Aerospace_Studies" },
      {
        value: "african_african-american_stu",
        text: "African_African-American_Stu",
      },
      { value: "agric_education", text: "Agric_Education" },
      {
        value: "agric_extension_ed_evaluat",
        text: "Agric_Extension_Ed_Evaluat",
      },
      { value: "agricultural_economics", text: "Agricultural_Economics" },
      {
        value: "agricultural_economics_agrib",
        text: "Agricultural_Economics_Agrib",
      },
      { value: "agriculture", text: "Agriculture" },
      {
        value: "agri,_extension_adult_educat",
        text: "Agri,_Extension_Adult_Educat",
      },
      { value: "agronomy", text: "Agronomy" },
      { value: "animal_sciences", text: "Animal_Sciences" },
      { value: "anthropology", text: "Anthropology" },
      { value: "arabic", text: "Arabic" },
      { value: "architecture", text: "Architecture" },
      { value: "art", text: "Art" },
      { value: "art_history", text: "Art_History" },
      { value: "astronomy", text: "Astronomy" },
      { value: "athletic_training", text: "Athletic_Training" },
      { value: "audio-visual_arts", text: "Audio-Visual_Arts" },
      { value: "basic_sciences", text: "Basic_Sciences" },
      { value: "biological_engineering", text: "Biological_Engineering" },
      { value: "biological_sciences", text: "Biological_Sciences" },
      { value: "business_administration", text: "Business_Administration" },
      { value: "business_education", text: "Business_Education" },
      { value: "business_law", text: "Business_Law" },
      { value: "chemical_engineering", text: "Chemical_Engineering" },
      { value: "chemistry", text: "Chemistry" },
      { value: "child_and_family_studies", text: "Child_And_Family_Studies" },
      { value: "chinese", text: "Chinese" },
      { value: "civil_engineering", text: "Civil_Engineering" },
      {
        value: "civil_environmental_engineer",
        text: "Civil_Environmental_Engineer",
      },
      { value: "classical_studies", text: "Classical_Studies" },
      { value: "communication_disorders", text: "Communication_Disorders" },
      { value: "communication_studies", text: "Communication_Studies" },
      {
        value: "comparative_biomedical_science",
        text: "Comparative_Biomedical_Science",
      },
      { value: "comparative_literature", text: "Comparative_Literature" },
      { value: "computer_science", text: "Computer_Science" },
      { value: "construction_management", text: "Construction_Management" },
      { value: "curriculum_instruction", text: "Curriculum_Instruction" },
      { value: "dairy_science", text: "Dairy_Science" },
      {
        value: "digital_media_arts_engineeri",
        text: "Digital_Media_Arts_Engineeri",
      },
      {
        value: "disaster_science_management",
        text: "Disaster_Science_Management",
      },
      { value: "doctor_of_design", text: "Doctor_Of_Design" },
      { value: "economics", text: "Economics" },
      {
        value: "educ_leadership_research_couns",
        text: "Educ_Leadership_Research_Couns",
      },
      { value: "education", text: "Education" },
      { value: "electrical_engineering", text: "Electrical_Engineering" },
      { value: "engineering", text: "Engineering" },
      { value: "english", text: "English" },
      { value: "entomology", text: "Entomology" },
      { value: "entrepreneurship", text: "Entrepreneurship" },
      { value: "environmental_engineering", text: "Environmental_Engineering" },
      {
        value: "environmental_management_systems",
        text: "Environmental_Management_Systems",
      },
      { value: "environmental_sciences", text: "Environmental_Sciences" },
      { value: "environmental_studies", text: "Environmental_Studies" },
      {
        value: "epidemiology_community_health",
        text: "Epidemiology_Community_Health",
      },
      { value: "experimental_statistics", text: "Experimental_Statistics" },
      { value: "extension_education", text: "Extension_Education" },
      { value: "film_media_arts", text: "Film_Media_Arts" },
      { value: "finance", text: "Finance" },
      { value: "fisheries", text: "Fisheries" },
      { value: "food_science", text: "Food_Science" },
      { value: "forestry", text: "Forestry" },
      { value: "french", text: "French" },
      { value: "french_studies", text: "French_Studies" },
      { value: "freshman_forum", text: "Freshman_Forum" },
      { value: "freshman_seminar", text: "Freshman_Seminar" },
      { value: "general_business", text: "General_Business" },
      { value: "geography", text: "Geography" },
      { value: "geology", text: "Geology" },
      { value: "german", text: "German" },
      { value: "greek", text: "Greek" },
      { value: "hebrew", text: "Hebrew" },
      { value: "history", text: "History" },
      { value: "home_econ_educ", text: "Home_Econ_Educ" },
      { value: "honors", text: "Honors" },
      { value: "horticulture", text: "Horticulture" },
      { value: "how_to_do_lsu", text: "How_To_Do_Lsu" },
      { value: "human_ecology", text: "Human_Ecology" },
      { value: "human_resource_education", text: "Human_Resource_Education" },
      { value: "human_sciences_education", text: "Human_Sciences_Education" },
      { value: "humanities", text: "Humanities" },
      {
        value: "humanities_and_social_sciences",
        text: "Humanities_And_Social_Sciences",
      },
      { value: "industrial_education", text: "Industrial_Education" },
      { value: "industrial_engineering", text: "Industrial_Engineering" },
      { value: "industrial_technology", text: "Industrial_Technology" },
      {
        value: "industrial_manufacture_engineering",
        text: "Industrial_Manufacture_Engineering",
      },
      {
        value: "info_systems_and_decision_science",
        text: "Info_Systems_And_Decision_Science",
      },
      { value: "interior_design", text: "Interior_Design" },
      { value: "international_studies", text: "International_Studies" },
      { value: "italian", text: "Italian" },
      { value: "japanese", text: "Japanese" },
      { value: "junior_division", text: "Junior_Division" },
      { value: "kinesiology", text: "Kinesiology" },
      { value: "landscape_architecture", text: "Landscape_Architecture" },
      { value: "latin", text: "Latin" },
      {
        value: "leadership_human_resources_d",
        text: "Leadership_Human_Resources_D",
      },
      { value: "liberal_arts", text: "Liberal_Arts" },
      {
        value: "library_information_science",
        text: "Library_Information_Science",
      },
      { value: "life_course_and_aging", text: "Life_Course_And_Aging" },
      { value: "life_course_in_aging", text: "Life_Course_In_Aging" },
      { value: "linguistics", text: "Linguistics" },
      { value: "management", text: "Management" },
      { value: "marketing", text: "Marketing" },
      { value: "mass_communication", text: "Mass_Communication" },
      { value: "mathematics", text: "Mathematics" },
      { value: "mechanical_engineering", text: "Mechanical_Engineering" },
      { value: "medical_physics", text: "Medical_Physics" },
      { value: "military_science", text: "Military_Science" },
      { value: "music", text: "Music" },
      { value: "music_education", text: "Music_Education" },
      { value: "nuclear_science", text: "Nuclear_Science" },
      { value: "nutrition_food_sciences", text: "Nutrition_Food_Sciences" },
      {
        value: "oceanography_coastal_science",
        text: "Oceanography_Coastal_Science",
      },
      { value: "pathobiological_sciences", text: "Pathobiological_Sciences" },
      { value: "petroleum_engineering", text: "Petroleum_Engineering" },
      { value: "philosophy", text: "Philosophy" },
      {
        value: "philosophy_religious_studies",
        text: "Philosophy_Religious_Studies",
      },
      { value: "physical_science", text: "Physical_Science" },
      { value: "physics", text: "Physics" },
      { value: "plant_health", text: "Plant_Health" },
      { value: "political_science", text: "Political_Science" },
      { value: "portuguese", text: "Portuguese" },
      { value: "poultry_science", text: "Poultry_Science" },
      { value: "psychology", text: "Psychology" },
      { value: "public_administration", text: "Public_Administration" },
      { value: "religious_studies", text: "Religious_Studies" },
      {
        value: "renewable_natural_resources",
        text: "Renewable_Natural_Resources",
      },
      { value: "russian", text: "Russian" },
      { value: "science", text: "Science" },
      { value: "screen_arts", text: "Screen_Arts" },
      { value: "social_work", text: "Social_Work" },
      { value: "sociology", text: "Sociology" },
      { value: "spanish", text: "Spanish" },
      { value: "speech_communication", text: "Speech_Communication" },
      { value: "student_support_services", text: "Student_Support_Services" },
      { value: "swahili", text: "Swahili" },
      { value: "systems_science", text: "Systems_Science" },
      {
        value: "textiles,apparel_merchandise",
        text: "Textiles,Apparel_Merchandise",
      },
      { value: "theatre", text: "Theatre" },
      { value: "university", text: "University" },
      { value: "university_college", text: "University_College" },
      { value: "university_studies", text: "University_Studies" },
      { value: "veterinary_anatomy", text: "Veterinary_Anatomy" },
      {
        value: "veterinary_clinical_sciences",
        text: "Veterinary_Clinical_Sciences",
      },
      { value: "veterinary_medicine", text: "Veterinary_Medicine" },
      {
        value: "veterinary_microbiol_parasit",
        text: "Veterinary_Microbiol_Parasit",
      },
      { value: "veterinary_pathology", text: "Veterinary_Pathology" },
      {
        value: "veterinary_physiol,_pharmacy",
        text: "VeterinaryPhysiol Pharmacy",
      },
      { value: "veterinary_science", text: "Veterinary Science" },
      { value: "vocational_education", text: "Vocational Education" },
      { value: "vocational_trade_ind_ed", text: "Vocational Trade Ind Ed" },
      { value: "wildlife", text: "Wildlife" },
      {
        value: "women's_and_gender_studies",
        text: "Women'S_And_Gender_Studies",
      },
    ],
  },
  {
    name: "core_issue",
    options: [
      { value: "broken_screen", text: "Broken Screen" },
      { value: "expanded_battery", text: "Expanded Battery" },
      { value: "faulty_ram", text: "Faulty RAM" },
      { value: "network_problem", text: "Network Problem" },
      { value: "post_error", text: "Post Error" },
      { value: "virus_infection", text: "Malware or Spyware Infection" },
      { value: "system_overheat", text: "System overheating" },
      { value: "system_crash", text: "System Crash" },
    ],
  },
  {
    name: "component",
    options: [
      { value: "cpu", text: "CPU" },
      { value: "ram", text: "RAM" },
      { value: "case", text: "Case" },
      { value: "storage_device", text: "Storage Device" },
      { value: "power_supply", text: "Power Supply" },
      { value: "gpu", text: "GPU" },
      { value: "motherboard", text: "Motherboard" },
      { value: "heatsink", text: "Heatsink" },
      { value: "case_fans", text: "Case Fans" },
      { value: "usb_port", text: "USB Port" },
    ],
  },
  {
    name: "status",
    options: [
      /* Status must be OPEN or CLOSE for db */
      { value: "OPEN", text: "Open" },
      { value: "CLOSE", text: "Closed" },
    ],
  },
];
