export const genRandomNumber = (min: number, max: number): number =>
  Math.floor(Math.random() * (max - min + 1)) + min;

type GetRandomName = () => { first: string; last: string };
export const genRandomName: GetRandomName = () => {
  const _first = [
    'Adam',
    'Alex',
    'Aaron',
    'Ben',
    'Carl',
    'Dan',
    'David',
    'Edward',
    'Fred',
    'Frank',
    'George',
    'Hal',
    'Hank',
    'Ike',
    'John',
    'Jack',
    'Joe',
    'Larry',
    'Monte',
    'Matthew',
    'Mark',
    'Nathan',
    'Otto',
    'Paul',
    'Peter',
    'Roger',
    'Roger',
    'Steve',
    'Thomas',
    'Tim',
    'Ty',
    'Victor',
    'Walter',
  ];
  const _last = [
    'Anderson',
    'Ashwoon',
    'Aikin',
    'Bateman',
    'Bongard',
    'Bowers',
    'Boyd',
    'Cannon',
    'Cast',
    'Deitz',
    'Dewalt',
    'Ebner',
    'Frick',
    'Hancock',
    'Haworth',
    'Hesch',
    'Hoffman',
    'Kassing',
    'Knutson',
    'Lawless',
    'Lawicki',
    'Mccord',
    'McCormack',
    'Miller',
    'Myers',
    'Nugent',
    'Ortiz',
    'Orwig',
    'Ory',
    'Paiser',
    'Pak',
    'Pettigrew',
    'Quinn',
    'Quizoz',
    'Ramachandran',
    'Resnick',
    'Sagar',
    'Schickowski',
    'Schiebel',
    'Sellon',
    'Severson',
    'Shaffer',
    'Solberg',
    'Soloman',
    'Sonderling',
    'Soukup',
    'Soulis',
    'Stahl',
    'Sweeney',
    'Tandy',
    'Trebil',
    'Trusela',
    'Trussel',
    'Turco',
    'Uddin',
    'Uflan',
    'Ulrich',
    'Upson',
    'Vader',
    'Vail',
    'Valente',
    'Van Zandt',
    'Vanderpoel',
    'Ventotla',
    'Vogal',
    'Wagle',
    'Wagner',
    'Wakefield',
    'Weinstein',
    'Weiss',
    'Woo',
    'Yang',
    'Yates',
    'Yocum',
    'Zeaser',
    'Zeller',
    'Ziegler',
    'Bauer',
    'Baxster',
    'Casal',
    'Cataldi',
    'Caswell',
    'Celedon',
    'Chambers',
    'Chapman',
    'Christensen',
    'Darnell',
    'Davidson',
    'Davis',
    'DeLorenzo',
    'Dinkins',
    'Doran',
    'Dugelman',
    'Dugan',
    'Duffman',
    'Eastman',
    'Ferro',
    'Ferry',
    'Fletcher',
    'Fietzer',
    'Hylan',
    'Hydinger',
    'Illingsworth',
    'Ingram',
    'Irwin',
    'Jagtap',
    'Jenson',
    'Johnson',
    'Johnsen',
    'Jones',
    'Jurgenson',
    'Kalleg',
    'Kaskel',
    'Keller',
    'Leisinger',
    'LePage',
    'Lewis',
    'Linde',
    'Lulloff',
    'Maki',
    'Martin',
    'McGinnis',
    'Mills',
    'Moody',
    'Moore',
    'Napier',
    'Nelson',
    'Norquist',
    'Nuttle',
    'Olson',
    'Ostrander',
    'Reamer',
    'Reardon',
    'Reyes',
    'Rice',
    'Ripka',
    'Roberts',
    'Rogers',
    'Root',
    'Sandstrom',
    'Sawyer',
    'Schlicht',
    'Schmitt',
    'Schwager',
    'Schutz',
    'Schuster',
    'Tapia',
    'Thompson',
    'Tiernan',
    'Tisler',
  ];

  const random = (size: number) => Math.floor(Math.random() * size);
  return {
    first: _first[random(_first.length)],
    last: _last[random(_last.length)],
  };
};

export const genRandomDepartment = () => {
  const departments = [
    'ACCOUNTING',
    'ADMINISTRATIVE & FOUNDATION SE',
    'AEROSPACE STUDIES',
    'AFRICAN & AFRICAN-AMERICAN STU',
    'AGRIC EDUCATION',
    'AGRIC & EXTENSION ED & EVALUAT',
    'AGRICULTURAL ECONOMICS',
    'AGRICULTURAL ECONOMICS & AGRIB',
    'AGRICULTURE',
    'AGRI, EXTENSION & ADULT EDUCAT',
    'AGRONOMY',
    'ANIMAL SCIENCES',
    'ANTHROPOLOGY',
    'ARABIC',
    'ARCHITECTURE',
    'ART',
    'ART HISTORY',
    'ASTRONOMY',
    'ATHLETIC TRAINING',
    'AUDIO-VISUAL ARTS',
    'BASIC SCIENCES',
    'BIOLOGICAL ENGINEERING',
    'BIOLOGICAL SCIENCES',
    'BUSINESS ADMINISTRATION',
    'BUSINESS EDUCATION',
    'BUSINESS LAW',
    'CHEMICAL ENGINEERING',
    'CHEMISTRY',
    'CHILD AND FAMILY STUDIES',
    'CHINESE',
    'CIVIL ENGINEERING',
    'CIVIL & ENVIRONMENTAL ENGINEER',
    'CLASSICAL STUDIES',
    'COMMUNICATION DISORDERS',
    'COMMUNICATION STUDIES',
    'COMPARATIVE BIOMEDICAL SCIENCE',
    'COMPARATIVE LITERATURE',
    'COMPUTER SCIENCE',
    'CONSTRUCTION MANAGEMENT',
    'CURRICULUM & INSTRUCTION',
    'DAIRY SCIENCE',
    'DIGITAL MEDIA ARTS & ENGINEERI',
    'DISASTER SCIENCE MANAGEMENT',
    'DOCTOR OF DESIGN',
    'ECONOMICS',
    'EDUC LEADERSHIP RESEARCH COUNS',
    'EDUCATION',
    'ELECTRICAL ENGINEERING',
    'ENGINEERING',
    'ENGLISH',
    'ENTOMOLOGY',
    'ENTREPRENEURSHIP',
    'ENVIRONMENTAL ENGINEERING',
    'ENVIRONMENTAL MANAGEMENT SYSTE',
    'ENVIRONMENTAL SCIENCES',
    'ENVIRONMENTAL STUDIES',
    'EPIDEMIOLOGY & COMMUNITY HEALT',
    'EXPERIMENTAL STATISTICS',
    'EXTENSION EDUCATION',
    'FILM & MEDIA ARTS',
    'FINANCE',
    'FISHERIES',
    'FOOD SCIENCE',
    'FORESTRY',
    'FRENCH',
    'FRENCH STUDIES',
    'FRESHMAN FORUM',
    'FRESHMAN SEMINAR',
    'GENERAL BUSINESS',
    'GEOGRAPHY',
    'GEOLOGY',
    'GERMAN',
    'GREEK',
    'HEBREW',
    'HISTORY',
    'HOME ECON EDUC',
    'HONORS',
    'HORTICULTURE',
    'HOW TO DO LSU',
    'HUMAN ECOLOGY',
    'HUMAN RESOURCE EDUCATION',
    'HUMAN SCIENCES & EDUCATION',
    'HUMANITIES',
    'HUMANITIES AND SOCIAL SCIENCES',
    'INDUSTRIAL EDUCATION',
    'INDUSTRIAL ENGINEERING',
    'INDUSTRIAL TECHNOLOGY',
    'INDUSTRIAL & MANUFACTUR ENGINE',
    'INFO SYSTEMS AND DECISION SCIE',
    'INTERIOR DESIGN',
    'INTERNATIONAL STUDIES',
    'ITALIAN',
    'JAPANESE',
    'JUNIOR DIVISION',
    'KINESIOLOGY',
    'LANDSCAPE ARCHITECTURE',
    'LATIN',
    'LEADERSHIP & HUMAN RESOURCES D',
    'LIBERAL ARTS',
    'LIBRARY & INFORMATION SCIENCE',
    'LIFE COURSE AND AGING',
    'LIFE COURSE IN AGING',
    'LINGUISTICS',
    'MANAGEMENT',
    'MARKETING',
    'MASS COMMUNICATION',
    'MATHEMATICS',
    'MECHANICAL ENGINEERING',
    'MEDICAL PHYSICS',
    'MILITARY SCIENCE',
    'MUSIC',
    'MUSIC EDUCATION',
    'NUCLEAR SCIENCE',
    'NUTRITION & FOOD SCIENCES',
    'OCEANOGRAPHY & COASTAL SCIENCE',
    'PATHOBIOLOGICAL SCIENCES',
    'PETROLEUM ENGINEERING',
    'PHILOSOPHY',
    'PHILOSOPHY & RELIGIOUS STUDIES',
    'PHYSICAL SCIENCE',
    'PHYSICS',
    'PLANT HEALTH',
    'POLITICAL SCIENCE',
    'PORTUGUESE',
    'POULTRY SCIENCE',
    'PSYCHOLOGY',
    'PUBLIC ADMINISTRATION',
    'RELIGIOUS STUDIES',
    'RENEWABLE NATURAL RESOURCES',
    'RUSSIAN',
    'SCIENCE',
    'SCREEN ARTS',
    'SOCIAL WORK',
    'SOCIOLOGY',
    'SPANISH',
    'SPEECH COMMUNICATION',
    'STUDENT SUPPORT SERVICES',
    'SWAHILI',
    'SYSTEMS SCIENCE',
    'TEXTILES,APPAREL & MERCHANDISI',
    'THEATRE',
    'UNIVERSITY',
    'UNIVERSITY COLLEGE',
    'UNIVERSITY STUDIES',
    'VETERINARY ANATOMY',
    'VETERINARY CLINICAL SCIENCES',
    'VETERINARY MEDICINE',
    'VETERINARY MICROBIOL & PARASIT',
    'VETERINARY PATHOLOGY',
    'VETERINARY PHYSIOL, PHARMAC &',
    'VETERINARY SCIENCE',
    'VOCATIONAL EDUCATION',
    'VOCATIONAL TRADE & IND ED',
    'WILDLIFE',
    "WOMEN'S AND GENDER STUDIES",
  ];
  const random = (size: number) => Math.floor(Math.random() * size);
  return departments[random(departments.length)];
};
